-- Remove / withdraw a player from a tournament (and optionally cleanup matches)
-- IMPORTANT:
-- - Do NOT delete the player from `players` (they may exist in other tournaments/leagues).
-- - Choose ONE of the modes below based on tournament state.
--
-- Fill these placeholders:
--   'TOURNAMENT_ID_HERE'
--   'PLAYER_ID_HERE'
--
-- Tables involved:
-- - tournament_players (membership)
-- - group_players (group membership)
-- - groups (group stage structure)
-- - matches (group + playoff matches; group matches typically have group_id; playoff matches can have tournament_id)
--
-- Notes about cascading:
-- - Deleting matches cascades to `legs`, `dart_throws`, and `match_player_stats` (based on your schema).
-- - Deleting groups cascades to group matches and group_players (and then further cascades).
--
-- -----------------------------
-- 0) Inspect current situation
-- -----------------------------
-- SELECT id, name, status FROM tournaments WHERE id = 'TOURNAMENT_ID_HERE';
-- SELECT COUNT(*) AS group_count FROM groups WHERE tournament_id = 'TOURNAMENT_ID_HERE';
-- SELECT
--   COUNT(*) FILTER (WHERE status = 'completed') AS completed_matches,
--   COUNT(*) FILTER (WHERE status <> 'completed') AS non_completed_matches
-- FROM matches
-- WHERE tournament_id = 'TOURNAMENT_ID_HERE'
--   AND (player1_id = 'PLAYER_ID_HERE' OR player2_id = 'PLAYER_ID_HERE');
--
-- SELECT *
-- FROM tournament_players
-- WHERE tournament_id = 'TOURNAMENT_ID_HERE' AND player_id = 'PLAYER_ID_HERE';
--
-- --------------------------------------------
-- MODE A) Tournament NOT started yet
-- (status = 'open_for_registration' OR no groups created)
-- Best: just remove membership, and you're done.
-- --------------------------------------------
-- BEGIN;
--   DELETE FROM tournament_players
--   WHERE tournament_id = 'TOURNAMENT_ID_HERE'
--     AND player_id = 'PLAYER_ID_HERE';
--
--   -- If groups were somehow pre-created, also remove from group_players:
--   DELETE FROM group_players
--   WHERE player_id = 'PLAYER_ID_HERE'
--     AND group_id IN (
--       SELECT id FROM groups WHERE tournament_id = 'TOURNAMENT_ID_HERE'
--     );
-- COMMIT;
--
-- ------------------------------------------------------------
-- MODE B) Tournament started, but NO matches played yet
-- (groups exist, but all matches are still pending)
-- Best: delete the groups (wipes group matches), remove the player,
-- then re-start tournament in UI to regenerate balanced groups/matches.
-- ------------------------------------------------------------
-- BEGIN;
--   -- Wipe group stage structure (cascades group_matches + group_players)
--   DELETE FROM groups
--   WHERE tournament_id = 'TOURNAMENT_ID_HERE';
--
--   -- Remove player from tournament
--   DELETE FROM tournament_players
--   WHERE tournament_id = 'TOURNAMENT_ID_HERE'
--     AND player_id = 'PLAYER_ID_HERE';
--
--   -- Optional: if playoff matches already exist for this tournament, remove them too
--   -- (only if you haven't started playoffs yet)
--   -- DELETE FROM matches
--   -- WHERE tournament_id = 'TOURNAMENT_ID_HERE'
--   --   AND is_playoff = true;
--
--   -- Optional: set tournament status back to open registration if you want
--   -- UPDATE tournaments SET status = 'open_for_registration' WHERE id = 'TOURNAMENT_ID_HERE';
-- COMMIT;
--
-- -------------------------------------------------------------------
-- MODE C) Matches already played (recommended: WITHDRAW/forfeit remaining)
-- This preserves historical results, but makes remaining scheduled matches
-- vs the withdrawn player end immediately.
--
-- This will:
-- - Remove player from tournament_players and group_players (so UI/player lists update)
-- - Mark NON-completed matches involving the player as completed with opponent as winner
-- - Write a minimal `result` JSON so standings/statistics logic can handle it
--
-- NOTE: This will affect standings (opponents get wins/legs) but keeps past matches.
-- -------------------------------------------------------------------
-- BEGIN;
--   -- Remove membership
--   DELETE FROM tournament_players
--   WHERE tournament_id = 'TOURNAMENT_ID_HERE'
--     AND player_id = 'PLAYER_ID_HERE';
--
--   DELETE FROM group_players
--   WHERE player_id = 'PLAYER_ID_HERE'
--     AND group_id IN (
--       SELECT id FROM groups WHERE tournament_id = 'TOURNAMENT_ID_HERE'
--     );
--
--   -- Forfeit any remaining (non-completed) group matches for this tournament
--   UPDATE matches
--   SET
--     status = 'completed',
--     winner_id = CASE WHEN player1_id = 'PLAYER_ID_HERE' THEN player2_id ELSE player1_id END,
--     player1_legs = CASE WHEN player1_id = 'PLAYER_ID_HERE' THEN 0 ELSE COALESCE(legs_to_win, 3) END,
--     player2_legs = CASE WHEN player2_id = 'PLAYER_ID_HERE' THEN 0 ELSE COALESCE(legs_to_win, 3) END,
--     completed_at = NOW(),
--     updated_at = NOW(),
--     result = jsonb_build_object(
--       'winner', CASE WHEN player1_id = 'PLAYER_ID_HERE' THEN player2_id ELSE player1_id END,
--       'player1Legs', CASE WHEN player1_id = 'PLAYER_ID_HERE' THEN 0 ELSE COALESCE(legs_to_win, 3) END,
--       'player2Legs', CASE WHEN player2_id = 'PLAYER_ID_HERE' THEN 0 ELSE COALESCE(legs_to_win, 3) END
--     )
--   WHERE tournament_id = 'TOURNAMENT_ID_HERE'
--     AND is_playoff = false
--     AND status <> 'completed'
--     AND (player1_id = 'PLAYER_ID_HERE' OR player2_id = 'PLAYER_ID_HERE');
--
-- COMMIT;
--

